#!/usr/bin/env bash
# mise description="Deploy"
# mise depends=["deps"]

set +x

REQUIRED_VARS=('BUNNY_BLOG_PASSWORD')

for var in "${REQUIRED_VARS[@]}"
do
  if [[ ! -v $var ]]; then
    echo "\$${var} needs to be set."
    exit 1
  fi
done

npx bnycdn key -t storages set medium-place $BUNNY_BLOG_PASSWORD

earthly +release
npx bnycdn cp -s medium-place -R --from=./dist/ --to=./medium-place/
